config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "registrations" }

  resources :users do
    resources :posts do
      resources :comments
    end
  end
  resources :posts, only: :index

  root to: "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :post 
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :thumbnail, AvatarUploader
  validates :content, presence: true
  validates :title, presence: true
  validates :lead_paragraph, presence: true
  belongs_to :user
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  
  mount_uploader :avatar, AvatarUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
#  before_action :configure_permitted_parameters, if: :devise_controller?
#  protected
#
#  def configure_permitted_parameters
#    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password) }
#  end
  private
 
    def after_sign_in_path_for(resource)
       posts_url
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(params[:comment].permit!)
    @post = Post.find(params[:post_id])

    @comment.user = current_user
    @comment.post = @post
    @comment.save
    redirect_to [@comment.user,@comment.post]
  end

  def destroy
    
    @comment = Comment.find params[:id]
    @post = Post.find(params[:post_id])
    
    @comment.user = current_user
    @comment.post = @post
    @comment.destroy
    redirect_to [@comment.user,@comment.post]
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, :except=>[:index,:show]
  def index
    @post = Post.all
  end

  def show
    load_user
    load_post
  end

  def edit
    load_user
    load_post
    
  end

  def update
    load_post
    load_user
    if @post.update_attributes(post_params)
      render 'show'
    else
      render 'show'
    end
  end

  def new
    load_user
    @post = Post.new
  end

  def create
    load_user
    @post = Post.new(post_params)
    if @post.save
      redirect_to['@user,:posts,index']
    else
      render 'new'
    end
  end

  def destroy
    load_post
    load_user
    @post.destroy
    render 'index'
  end

  protected
  def load_user
    @user = User.find(params[:user_id])
  end

  def load_post
    @post = Post.find params[:id]
  end

  def post_params
    params.require(:post).permit(:title, :content, :lead_paragraph, :user_id, :thumbnail)
  end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
#  before_filter :configure_permitted_parameters, :only => [:create]
  
  private
    def sign_up_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation,:avatar)
    end
    
    def after_sign_up_path_for(resource)
      "/users/sign_in"
    end
 
    def after_inactive_sign_up_path_for(resource)
      "/users/sign_in"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :except=>[:index, :show]
    
  def show
    load_user
  end

  def edit
    load_user
  end

  def update
    load_user
    if @user.update_attributes(user_params)
      redirect_to[':show']
    else
      redirect_to[':edit']
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to[':index']
    else
      redirect_to[':new']
    end
  end

  def destroy
    load_user
    @user.destroy
    render 'index'
  end

  def user_params
    params[:user].permit(:first_name, :last_name, :email, :password, :password_confirmation, :avatar)
  end

  protected
  def load_user
    @user = User.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RubyProject</title>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= stylesheet_link_tag    'materialize', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'jquery-3.1.1.min', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'materialize', 'data-turbolinks-track' => true %>
  
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav>
        <ul>
            <li><a href="/">Posts</a></li>
            <li><a href="/users/">Users</a></li>
            <% if user_signed_in? %>
                <li class="right"><%= link_to('Logout',destroy_user_session_path, {:method => :delete}) %></li>
                <li class="right">Bonjour, <%= link_to(current_user.email,current_user,{:id => :userProfile}) %></li>
            <% else %>
                 <li class="right"><%= link_to('Sign up', new_user_registration_path)%></li>
                 <li class="right"><%= link_to('Login',new_user_session_path)%></li>
            <% end %>
        </ul>
    </nav>

<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>


  <%= yield %>


</body>
</html>

app/views/posts/_form.html.haml
=form_for [@user,@post] do |f|
    = f.label 'Title:'
    = f.text_field :title,:required => true
    <br>
    = f.label 'Lead paragraph:'
    = f.text_field :lead_paragraph,:required => true
    <br>
    = f.label 'Content:'
    = f.text_field :content,:required => true
    <br>
    - if @post.thumbnail.url.present?
        = image_tag @post.thumbnail.thumb.url

    = f.label 'Thumbnail:'
    = f.file_field :thumbnail
    
    = f.hidden_field :user_id, value: @user.id
    <br>
    <br>
    =f.submit "Validate", class: "btn"

app/views/posts/edit.html.haml
%section

	=link_to "Back", [:user,:post], { :class=>"btn" }

	%h2= "Edit post"
	= render(:partial => "form")

app/views/posts/index.html.haml
%div
    - if current_user
        <br>
        =link_to "Create post", new_user_post_path(current_user), {:class => "btn"}
    %h2 Posts list :
    %ul
        -Post.all.order("created_at desc").each do |post|
            %section{:class => "posts"}
                - if post.thumbnail.url.present?
                    = image_tag "#{post.thumbnail.thumb.url}"
                %div{:class => "post_precontent"}
                    %div 
                        =link_to "#{post.title}", [post.user, post]
                        <span> Written by:
                        =link_to "#{post.user.first_name} #{post.user.last_name}", post.user
                        </span>
                        <br>
                        %span= "Date: #{post.created_at}"
                    %p= "#{post.lead_paragraph}"

app/views/posts/new.html.haml
%section
	=link_to "Back to posts", [:user,:posts], { :class=>"btn" }
    
	%h2= "Create post"
	= render(:partial => "form")

app/views/posts/show.html.haml
%section

    =link_to "Back to posts", [:user,:posts], { :class=>"btn" }
    
    %div
        %h3= @post.title
        <span> Written by:
        =link_to "#{@post.user.first_name} #{@post.user.last_name}", @post.user
        </span>
        %span= "Date: #{@post.created_at}"
    %br
    %br
    - if @post.thumbnail.url.present?
        = image_tag "#{@post.thumbnail.url}"

    %p= @post.lead_paragraph
    %p= @post.content

    - if @post.user == current_user
        =link_to "Edit", [:edit, @post.user, @post], {:class=>"btn"}
        =link_to "Delete", [@post.user, @post],  {method: :delete, :class=>"btn"}

    - if current_user
        =form_for @comment = Comment.new, :html => {:class => "commenting"}, url:[@user, @post, @comment] do |c|
            = c.label 'Write a comment about it:'
            = c.text_field :content,:required => true
            = c.submit "Publish it!", class: "btn"

-if @post.comments.size == 0
    %p= "Be the first to write a comment !"
-else
    %h3= "Comments:"
    -@post.comments.order("created_at desc").each do |c|
        %section{:class => 'posts'}
            - if c.user.avatar.url.present?
                = image_tag "#{c.user.avatar.thumb_comment.url}"
            %div{:class => "post_precontent"}
                %div 
                    =link_to "#{c.user.first_name} #{c.user.last_name}", [c.user]
                    %span= "Date: #{c.created_at}"
            %p= c.content
            -if c.user == current_user
                =link_to "Delete", [@post.user,@post,c],  {method: :delete, :class=>"btn"}

            

app/views/users/_form.html.haml
=form_for [@user] do |f|
    = f.label 'Prenom:'
    = f.text_field :first_name,:required => true
    <br>
    = f.label 'Nom:'
    = f.text_field :last_name,:required => true
    <br>
    = f.label 'Email:'
    = f.email_field :email,:required => true
    <br>
    - if @user.avatar.url.present?
        = image_tag @user.avatar.thumb.url
    = f.label 'Avatar :'
    = f.file_field :avatar
    <br>
    <br>
    - if @user.new_record?
        = f.label 'Password (6 caracters minimum):'
        = f.password_field :password
        <br>
        = f.label 'Password confirmation:'
        = f.password_field :password_confirmation
        <br>
    =f.submit "Validate", class: "btn"

app/views/users/edit.html.haml
%section

	=link_to "Back to User", [:user], { :class=>"btn" }

	%h2= "Edit user"
	= render(:partial => "form")

app/views/users/index.html.haml
%section
    %h2 Users list :
    %ul
        -User.all.each do |usrs|
            %li
                = link_to "#{usrs.first_name} #{usrs.last_name}", [usrs]
                %span= " #{usrs.email}"

app/views/users/new.html.haml
%section
	=link_to "Back to Users list", [:users], { :class=>"btn" }

	%h2= "Create user"
	= render(:partial => "form")

app/views/users/show.html.haml
%section

    =link_to "Back to Users list", [:users], { :class=>"btn" }

    %h3= @user.first_name + ' ' + @user.last_name

    - if @user.avatar.url.present?
        = image_tag "#{@user.avatar.url}"

    %br
    %p= "Email : #{@user.email}"


    - if @user == current_user
        =link_to "Edit", edit_user_registration_path, {:class=>"btn"}

        =link_to "Delete", [@user],  {method: :delete, :class=>"btn"}
-if @user.posts.size == 0
    %p= "#{@user.first_name} #{@user.last_name} doesn't write posts yet."
-else 
    %h3= "Posts:"

    -@user.posts.order("created_at desc").each do |post|
        %section{:class => "posts"}
            - if post.thumbnail.url.present?
                = image_tag "#{post.thumbnail.thumb.url}"
            %div{:class => "post_precontent"}
                %div 
                    =link_to "#{post.title}", [post.user, post]
                    <span> Written by:
                    =link_to "#{post.user.first_name} #{post.user.last_name}", post.user
                    </span>
                    %span= "Date: #{post.created_at}"
                %p= "#{post.lead_paragraph}"